### ISSUE TITLE
Make exceptions for public URLs under /news-projects/

### ISSUE THREAD

**Issue by colingourlay** [abcnews/dev-proxy#1]
I'd like to be able to run the dev proxy on my chart builder, which is deployed to `/news-projects/`, but currently we never load proxies from anything on `www.abc.net.au` (understandably).

Could we possibly add a 2nd boolean argument to `proxy` that will allow it to run on `/news-projects/` URLs, regardless of the live/preview environment? It seems reasonably safe to do so, but I'd like your thoughts @drzax.

**Comment by drzax** [comment]
I think I agree it's reasonably safe to do. Another protection we could add, though, is only accept alternative scripts that live on and ABC subdomain (so, you'd need to be running the dev server on VPN for it to work.
